# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
Common:
  model: /models/hub/models--neuralmagic--DeepSeek-R1-Distill-Llama-70B-FP8-dynamic/snapshots/fb3637a1165cec3832958bd72ebbe04021601489
  block-size: 128
  kv-transfer-config: '{"kv_connector":"DynamoNixlConnector"}'

Frontend:
  served_model_name: DeepSeek-R1-Distill-Llama-70B-FP8-dynamic
  endpoint: dynamo.VllmWorker.generate
  port: 8000
  router: round-robin
  common-configs: [block-size]

VllmWorker:
  remote-prefill: true
  conditional-disagg: true
  max-local-prefill-length: 511
  max-prefill-queue-size: 8
  tensor-parallel-size: 2
  enable-prefix-caching: false
  gpu-memory-utilization: 0.96
  max-model-len: 16384
  ServiceArgs:
    workers: 1
    resources:
      gpu: 2
  common-configs: [model, block-size, kv-transfer-config]

PrefillWorker:
  max-model-len: 10000
  gpu-memory-utilization: 0.98
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1
  common-configs: [model, block-size, kv-transfer-config]

Prometheus:
  global:
    scrape_interval: 5s
  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'frontend'
      static_configs:
        - targets: ['localhost:8000']

Planner:
  adjustment-interval: 20
  environment: "local"
  no-operation: False
  profile-results-dir: "/workspace/dynamo-eval/tmp"
  isl: 1000
  osl: 200
  ttft: 1.5
  itl: 0.05
  load-predictor: "arima"
  decode-engine-num-gpu: 2
  prefill-engine-num-gpu: 1
  max-gpu-budget: 8
  type-planner: "planner_dynamo_load"
