# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v2
name: dynamo-helm-chart
maintainers:
  - name: NVIDIA, Inc.
    url: https://www.nvidia.com
description: A Helm chart for NVIDIA CompoundAI Platform.
type: application
version: 25.2.0-rc3
home: https://nvidia.com
dependencies:
  - name: dynamo-operator
    version: 0.1.7
    repository: file://components/operator
    condition: dynamo-operator.enabled
  - name: dynamo-api-store
    version: 0.1.0
    repository: file://components/api-store
    condition: dynamo-api-store.enabled
  - name: nats
    version: 1.3.2
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
  - name: etcd
    version: 11.1.0
    repository: "https://charts.bitnami.com/bitnami"
    condition: etcd.enabled
  - name: postgresql
    version: 16.6.2
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: minio
    version: 16.0.2
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
