# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Frontend:
  served_model_name: "nvidia/DeepSeek-R1-FP4"
  endpoint: dynamo.TensorRTLLMWorker.generate
  port: 8000
  router: round-robin

TensorRTLLMWorker:
  served_model_name: "nvidia/DeepSeek-R1-FP4"
  # NOTE: FP4 only supported starting with Blackwell GPUs.
  # https://huggingface.co/nvidia/DeepSeek-R1-FP4
  # You can also specify the full path to locally downloaded weights
  # instead of a HuggingFace ID here.
  model-path: "nvidia/DeepSeek-R1-FP4"
  # Path to a YAML file containing additional keyword arguments to pass to the TRTLLM engine.
  # The fields in `extra-engine-args` holds higher priority than the above TRTLLM engine fields.
  extra-engine-args: "configs/deepseek_r1/mtp/engine_configs/agg_config.yaml"
  router: round-robin
  ServiceArgs:
    workers: 1
    resources:
      gpu: 4
